### PR TITLE
Performance: Add ratios to results

### PR DESCRIPTION
**Pull request by daverigby**
Add a Gross and Net ratio column to aid in comparing the relative speed of Fleece & JSON.

### CODE REVIEW

**Comment by snej** [comment]
Thanks for adding this! It makes eyeballing the numbers a little confusing, though, because the values you added are "larger is better" whereas the existing numbers are "smaller is better". What do you think of inverting your figures so the comparisons are consistent?

**Comment by daverigby** [comment]
I originally had them inverted, problem was that the 28,000x number was so small (0.000035) that it seemed even more meaningless!

**Comment by daverigby** [comment]
(I don't mind either way, just seemed clearer as a multiplier).

**Comment by borrrden** [comment]
Unfortunately I really don't think anything is ever going to happen with this at this point, so I am going to close it.

**Pull request closed without merging**
